# Generated by Django 5.2.8 on 2025-11-25 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github_id', models.CharField(max_length=50, unique=True)),
                ('github_url', models.URLField()),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('contributor_type', models.CharField(choices=[('User', 'User'), ('Bot', 'Bot'), ('Organization', 'Organization')], default='User', max_length=20)),
                ('contributions', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-contributions', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='hackathon_banners')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('sponsor_note', models.TextField(blank=True, help_text='Additional information about sponsorship opportunities', null=True)),
                ('sponsor_link', models.URLField(blank=True, help_text='Link to sponsorship information or application', null=True)),
                ('owner', models.ForeignKey(help_text='User who created this hackathon', on_delete=django.db.models.deletion.CASCADE, related_name='owned_hackathons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='HackathonSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(help_text='Sponsor organization name', max_length=255)),
                ('sponsor_level', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner')], default='partner', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hackathon_sponsor_logos')),
                ('website', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='blt_hackathon.hackathon')),
            ],
            options={
                'ordering': ['sponsor_level', 'created'],
                'unique_together': {('hackathon', 'sponsor_name')},
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['owner', 'name'],
                'indexes': [models.Index(fields=['owner', 'name'], name='hackathon_repo_owner_name_idx')],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='hackathon',
            name='repositories',
            field=models.ManyToManyField(blank=True, related_name='hackathons', to='blt_hackathon.repository'),
        ),
        migrations.CreateModel(
            name='GitHubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('issue', 'Issue'), ('pull_request', 'Pull Request')], default='issue', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('is_merged', models.BooleanField(default=False)),
                ('github_url', models.URLField()),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hackathon.contributor')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='blt_hackathon.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HackathonPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(choices=[(1, 'First Place'), (2, 'Second Place'), (3, 'Third Place'), (4, 'Special Prize')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='blt_hackathon.hackathon')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='blt_hackathon.hackathonsponsor')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('hackathon', 'position')},
            },
        ),
        migrations.AddIndex(
            model_name='hackathon',
            index=models.Index(fields=['start_time'], name='hackathon_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='hackathon',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_hackathon_slug'),
        ),
        migrations.AddIndex(
            model_name='githubissue',
            index=models.Index(fields=['type', 'is_merged'], name='hackathon_issue_type_idx'),
        ),
        migrations.AddIndex(
            model_name='githubissue',
            index=models.Index(fields=['created_at'], name='hackathon_issue_created_idx'),
        ),
        migrations.AddIndex(
            model_name='githubissue',
            index=models.Index(fields=['merged_at'], name='hackathon_issue_merged_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='githubissue',
            unique_together={('issue_id', 'repo')},
        ),
    ]
